// dimsum-business/src/components/FooterSection.tsx
const FooterSection = () => {
  return (
    <footer id="contact" className="bg-dimsum-black text-white">
      <div className="container mx-auto px-4">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-12 py-16">
          {/* Logo & Description */}
          <div>
            <h3 className="font-serif text-2xl font-bold mb-4">
              Dim Sum Delight
            </h3>
            <p className="text-gray-300 mb-6">
              Authentic dim sum experience with handcrafted dumplings and
              traditional flavors.
            </p>
            <div className="flex space-x-4">
              <a
                href="https://www.facebook.com"
                target="_blank"
                className="text-gray-300 hover:text-dimsum transition-colors"
              >
                <svg
                  className="h-6 w-6"
                  fill="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path d="M22.675 0h-21.35c-.732 0-1.325.593-1.325 1.325v21.351c0 .731.593 1.324 1.325 1.324h11.495v-9.294h-3.128v-3.622h3.128v-2.671c0-3.1 1.893-4.788 4.659-4.788 1.325 0 2.463.099 2.795.143v3.24l-1.918.001c-1.504 0-1.795.715-1.795 1.763v2.313h3.587l-.467 3.622h-3.12v9.293h6.116c.73 0 1.323-.593 1.323-1.325v-21.35c0-.732-.593-1.325-1.325-1.325z" />
                </svg>
              </a>
              <a
                href="https://www.instagram.com"
                target="_blank"
                className="text-gray-300 hover:text-dimsum transition-colors"
              >
                <svg
                  className="h-6 w-6"
                  fill="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z" />
                </svg>
              </a>
              <a
                href="https://www.x.com"
                target="_blank"
                className="text-gray-300 hover:text-dimsum transition-colors"
              >
                <svg
                  className="h-6 w-6"
                  fill="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path d="M23.954 4.569c-.885.389-1.83.654-2.825.775 1.014-.611 1.794-1.574 2.163-2.723-.951.555-2.005.959-3.127 1.184-.896-.959-2.173-1.559-3.591-1.559-2.717 0-4.92 2.203-4.92 4.917 0 .39.045.765.127 1.124-4.09-.193-7.715-2.157-10.141-5.126-.427.722-.666 1.561-.666 2.457 0 1.819.924 3.42 2.326 4.356-.859-.01-1.667-.262-2.373-.652v.065c0 2.39 1.699 4.379 3.951 4.828-.414.115-.85.174-1.3.174-.317 0-.626-.03-.927-.086.631 1.953 2.445 3.377 4.604 3.417-1.68 1.319-3.809 2.105-6.102 2.105-.391 0-.779-.023-1.17-.067 2.189 1.394 4.768 2.209 7.557 2.209 9.054 0 14-7.503 14-13.992 0-.21 0-.42-.015-.63.961-.689 1.8-1.56 2.46-2.548l-.047-.02z" />
                </svg>
              </a>
            </div>
          </div>

          {/* Contact Info */}
          <div>
            <h4 className="text-xl font-bold mb-4">Contact Us</h4>
            <div className="space-y-3">
              <p>Merdeka Raya Street No 123</p>
              <p>Tebet, South Jakarta</p>
              <p>Phone: (+62) 123-456-7890</p>
              <p>Email: info@dimsumdelight.com</p>
            </div>
          </div>

          {/* Opening Hours */}
          <div>
            <h4 className="text-xl font-bold mb-4">Opening Hours</h4>
            <div className="space-y-3">
              <p>Monday - Thursday: 8AM - 9:30PM</p>
              <p>Friday - Saturday: 8AM - 10:30PM</p>
              <p>Sunday: 10AM - 9PM</p>
            </div>
          </div>

          {/* Newsletter */}
          <div>
            <h4 className="text-xl font-bold mb-4">Newsletter</h4>
            <p className="mb-4">
              Subscribe to receive updates on special offers and events.
            </p>
            <form className="flex flex-col sm:flex-row gap-2">
              <input
                type="email"
                placeholder="Your email"
                className="px-4 py-2 rounded-md text-gray-800 w-full"
              />
              <button
                type="submit"
                className="px-4 py-2 bg-dimsum text-white rounded-md hover:bg-dimsum-dark transition-colors whitespace-nowrap"
              >
                Subscribe
              </button>
            </form>
          </div>
        </div>

        <div className="py-6 border-t border-gray-700 text-center text-gray-400">
          <p>
            &copy; {new Date().getFullYear()} Dim Sum Delight. All rights
            reserved.
          </p>
        </div>
      </div>
    </footer>
  );
};

export default FooterSection;

// dental-clinic/src/components/FooterSection.vue
<script setup lang="ts">
import { ref } from "vue";

const currentYear = ref(new Date().getFullYear());

const navLinks = [
  { name: "Home", href: "#home" },
  { name: "Services", href: "#services" },
  { name: "About", href: "#about" },
  { name: "Team", href: "#team" },
  { name: "Testimonials", href: "#testimonials" },
  { name: "Gallery", href: "#gallery" },
  { name: "FAQ", href: "#faq" },
  { name: "Contact", href: "#contact" },
];

const subscribeEmail = ref("");
const isSubscribed = ref(false);

const subscribe = () => {
  // Simulate subscription
  setTimeout(() => {
    isSubscribed.value = true;
    subscribeEmail.value = "";
  }, 500);
};
</script>

<template>
  <footer class="bg-neutral-800 text-white pt-16 pb-8">
    <div class="container mx-auto px-4">
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-12">
        <div>
          <div class="flex items-center space-x-2 mb-6">
            <span class="text-primary-500 text-2xl">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-8 w-8"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z"
                />
              </svg>
            </span>
            <span class="font-heading font-bold text-2xl">DentalCare</span>
          </div>
          <p class="text-neutral-400 mb-6">
            Providing exceptional dental care with a gentle touch. Your smile is
            our priority.
          </p>
          <div class="flex space-x-4">
            <a
              href="#"
              class="text-neutral-400 hover:text-primary-500 transition-colors"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-5 w-5"
                fill="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"
                />
              </svg>
            </a>
            <a
              href="#"
              class="text-neutral-400 hover:text-primary-500 transition-colors"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-5 w-5"
                fill="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"
                />
              </svg>
            </a>
            <a
              href="#"
              class="text-neutral-400 hover:text-primary-500 transition-colors"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-5 w-5"
                fill="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"
                />
              </svg>
            </a>
            <a
              href="#"
              class="text-neutral-400 hover:text-primary-500 transition-colors"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-5 w-5"
                fill="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"
                />
              </svg>
            </a>
          </div>
        </div>

        <div>
          <h3 class="text-xl font-bold mb-6">Quick Links</h3>
          <ul class="space-y-3">
            <li v-for="link in navLinks" :key="link.name">
              <a
                :href="link.href"
                class="text-neutral-400 hover:text-primary-500 transition-colors"
                >{{ link.name }}</a
              >
            </li>
          </ul>
        </div>

        <div>
          <h3 class="text-xl font-bold mb-6">Services</h3>
          <ul class="space-y-3">
            <li>
              <a
                href="#services"
                class="text-neutral-400 hover:text-primary-500 transition-colors"
                >General Dentistry</a
              >
            </li>
            <li>
              <a
                href="#services"
                class="text-neutral-400 hover:text-primary-500 transition-colors"
                >Cosmetic Dentistry</a
              >
            </li>
            <li>
              <a
                href="#services"
                class="text-neutral-400 hover:text-primary-500 transition-colors"
                >Orthodontics</a
              >
            </li>
            <li>
              <a
                href="#services"
                class="text-neutral-400 hover:text-primary-500 transition-colors"
                >Pediatric Dentistry</a
              >
            </li>
            <li>
              <a
                href="#services"
                class="text-neutral-400 hover:text-primary-500 transition-colors"
                >Oral Surgery</a
              >
            </li>
            <li>
              <a
                href="#services"
                class="text-neutral-400 hover:text-primary-500 transition-colors"
                >Emergency Dental Care</a
              >
            </li>
          </ul>
        </div>

        <div>
          <h3 class="text-xl font-bold mb-6">Newsletter</h3>
          <p class="text-neutral-400 mb-6">
            Subscribe to our newsletter for dental tips and special offers.
          </p>

          <div v-if="isSubscribed" class="bg-neutral-700 rounded-lg p-4">
            <p class="text-green-400">
              Thank you for subscribing! You'll receive our next newsletter
              soon.
            </p>
          </div>

          <form v-else @submit.prevent="subscribe" class="flex">
            <input
              type="email"
              v-model="subscribeEmail"
              placeholder="Your email address"
              required
              class="flex-grow px-4 py-2 bg-neutral-700 rounded-l-lg border-0 focus:ring-2 focus:ring-primary-500 focus:outline-none text-white"
            />
            <button
              type="submit"
              class="bg-primary-500 text-white px-4 py-2 rounded-r-lg hover:bg-primary-600 transition-colors"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-5 w-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M13 7l5 5m0 0l-5 5m5-5H6"
                />
              </svg>
            </button>
          </form>
        </div>
      </div>

      <div class="border-t border-neutral-700 pt-8 mt-8">
        <div class="flex flex-col md:flex-row justify-between items-center">
          <p class="text-neutral-400 text-center md:text-left mb-4 md:mb-0">
            &copy; {{ currentYear }} DentalCare. All rights reserved.
          </p>
          <div class="flex space-x-6">
            <a
              href="#"
              class="text-neutral-400 hover:text-primary-500 transition-colors"
              >Privacy Policy</a
            >
            <a
              href="#"
              class="text-neutral-400 hover:text-primary-500 transition-colors"
              >Terms of Service</a
            >
            <a
              href="#"
              class="text-neutral-400 hover:text-primary-500 transition-colors"
              >Cookie Policy</a
            >
          </div>
        </div>
      </div>
    </div>
  </footer>
</template>
